version: '2'
services:
  solr:
    image: risdenk/solrj-jdbc-testing:solr
    ports:
      - 8983
      - 9983
      - 18983
    volumes:
      - /opt/solr

  jisql:
    image: risdenk/solrj-jdbc-testing:jisql
    depends_on:
      - solr
    volumes_from:
      - solr:ro
    environment:
      - "JDBC=jdbc:solr://solr:9983?collection=test"
      - "QUERY=select fielda, fieldb, fieldc, fieldd_s, fielde_i from test limit 10;"

  zeppelin:
    image: risdenk/solrj-jdbc-testing:zeppelin
    ports:
      - 8080
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  spark:
    image: risdenk/solrj-jdbc-testing:spark
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  spark2:
    image: risdenk/solrj-jdbc-testing:spark2
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  r-base:
    image: risdenk/solrj-jdbc-testing:r-base
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  rstudio:
    image: risdenk/solrj-jdbc-testing:rstudio
    ports:
      - 8787
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  jython:
    image: risdenk/solrj-jdbc-testing:jython
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  python:
    image: risdenk/solrj-jdbc-testing:python
    depends_on:
      - solr
    volumes_from:
      - solr:ro

  dbvisualizer:
    image: risdenk/solrj-jdbc-testing:dbvisualizer
    depends_on:
      - solr
    volumes_from:
      - solr:ro
    environment:
      - "DISPLAY=${X11_DISPLAY}"

  squirrelsql:
    image: risdenk/solrj-jdbc-testing:squirrelsql
    depends_on:
      - solr
    volumes_from:
      - solr:ro
    environment:
      - "DISPLAY=${X11_DISPLAY}"

